[package]
name = "bang-cli"
version = "3.0.0"
edition = "2021"

[dependencies]
bang = { path = "../lib" }
anstream = "0.6.4"
clap = { version = "4.4.8", features = ["derive"] }
owo-colors = "3.5.0"

[lints]
workspace = true
