[package]
name = "bang-parser"
version = "3.0.0"
edition = "2021"

[dependencies]
bumpalo = { version = "3.14.0", features = ["boxed", "collections"] }

[dev-dependencies]
indoc = "2.0.4"

[lints]
workspace = true
