[package]
name = "bang-lsp"
version = "3.0.0"
edition = "2021"

[dependencies]
bang-formatter = { path = "../formatter" }
bang-linter = { path = "../linter" }
bang-parser = { path = "../parser" }

lsp-server = "0.7.7"
lsp-types = "0.97.0"
serde_json = "1.0.128"

[lints]
workspace = true
