[package]
name = "bang-typechecker"
version = "3.0.0"
edition = "2021"

[dependencies]
bang-syntax = { path = "../syntax" }
bang-interpreter = { path = "../interpreter" }

[dev-dependencies]
indoc.workspace = true

[lints]
workspace = true
