[package]
name = "bang-typechecker"
version = "3.0.0"
edition = "2024"

[dependencies]
bang-syntax = { path = "../syntax" }
bang-stdlib = { path = "../stdlib" }
indoc.workspace = true

[lints]
workspace = true
