[package]
name = "bang-typechecker"
version = "3.0.0"
edition = "2024"

[dependencies]
bang-syntax = { path = "../syntax" }
bang-interpreter = { path = "../interpreter" }
indoc.workspace = true

[lints]
workspace = true
