[package]
name = "bang-formatter"
version = "3.0.0"
edition = "2024"

[dependencies]
bang-syntax = { path = "../syntax" }
bumpalo.workspace = true

[dev-dependencies]
indoc.workspace = true

[lints]
workspace = true
