[package]
name = "bang-formatter"
version = "3.0.0"
edition = "2021"

[dependencies]
bang-parser = { path = "../parser" }
bumpalo.workspace = true

[dev-dependencies]
indoc.workspace = true

[lints]
workspace = true
