name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add clippy rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --workspace
      - name: Lint
        run: cargo clippy --workspace -- -D warnings
      - name: Standard Library Documentation
        run: cargo run -p bang-stdlib --bin stdlib-docs -- --check
      - name: Test
        run: |
          cargo test --workspace --verbose
          cargo test -p bang-interpreter --verbose -F gc-stress-test

  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-symbolic-alignment-check
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: "Install Cargo Nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Test
        run: |
          cargo miri nextest run --no-fail-fast --workspace
          cargo miri nextest run -p bang-interpreter -F gc-stress-test --no-fail-fast
