name: CI
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup component add clippy rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --workspace
      - name: Lint
        run: cargo clippy --workspace -- -D warnings
      - name: Test
        run: |
          cargo test --workspace --verbose
          cargo test --workspace --verbose --features gc-stress-test
